#include <gb/cgb.h>
/*

 BGS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/
const uint16_t star_pal[]={
  RGB8(255, 252, 208), RGB8(127, 130, 80), RGB8(0, 0, 130), RGB8(0, 0, 0)
};
/* Start of tile array. */
const unsigned char BGs[] =
{
  0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF,
  0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF
};

/* End of BGS.C */
